### ISSUE TITLE
webpack-dev-server内存崩溃问题

### ISSUE THREAD

**Issue by harrydengchao** [sitorhy/react-webpack-boilerplate#3]
看到简书上您的文章写到`React编译样式比较慢，尤其通过import方式引用样式时，dev-server经常因爆内存而崩溃。`。

然后发现 scripts 中有两个命令 `start` and `dev`，分别使用的事 `express` and `webpack-dev-server`，这样做的用意是什么呢？是直接使用 express 的内存占用率会低一些吗，按理说不应该啊，我没发现类似文章，望指导。

**Comment by sitorhy** [comment]
express用来对比dev-server的，因为第一反应会以为是dev-server的问题，后来发现并没有太大关系，express也方便自己加配置，就没有删掉了。

harrydengchao <notifications@github.com> 于2020年3月17日周二 下午3:07写道：

**Comment by sitorhy** [comment]
express用来对比dev-server的，因为第一反应会以为是dev-server的问题，后来发现并没有太大关系，express也方便自己加配置，就没有删掉了。
